version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: nexus-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.backend
    container_name: nexus-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/nexusschedule
    depends_on:
      - mongodb

  ai-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile.ai-agent
    container_name: nexus-ai-agent
    ports:
      - "5001:5001"
    environment:
      - BACKEND_URL=http://backend:5000

  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.frontend
    container_name: nexus-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
